import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html lang="en">
      <meta httpEquiv="content-type" content="text/html;charset=UTF-8" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <title>HealthSpotLight</title>
      <meta name="robots" content="max-image-preview:large" />

      <Head>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script
          src="/wp-content/themes/weefly/assets/js/ajax-login-register6a4d.js"
          id="ajax-login-script-js"
        ></script>
        <script
          src="/wp-content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.minbd43.js"
          id="jquery-blockui-js"
        ></script>
        <script
          src="/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart.minbdeb.js"
          id="wc-add-to-cart-js"
        ></script>
        <script
          src="/wp-content/plugins/js_composer/assets/js/vendors/woocommerce-add-to-carte1b2.js"
          id="vc_woocommerce-add-to-cart-js-js"
        ></script>
        <script
          src="/wp-content/themes/weefly/assets/js/ajax-login-register.js"
          id="vb_reg_script-js"
        ></script>
        <script src="/template.js" id="ajax-login-script-js"></script>
        <link
          rel="alternate"
          type="application/rss+xml"
          title="Weefly &raquo; Feed"
          href="/feed/index.html"
        />
        <link
          rel="alternate"
          type="application/rss+xml"
          title="Weefly &raquo; Comments Feed"
          href="/comments/feed/index.html"
        />
        <link
          rel="stylesheet"
          id="simple-line-icon-css"
          href="/wp-content/themes/weefly/assets/css/simple-line-icons6a4d.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="sbi_styles-css"
          href="/wp-content/plugins/instagram-feed/css/sbi-styles.min6a4d.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="wp-block-library-css"
          href="/wp-includes/css/dist/block-library/style.min6a4d.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="wc-blocks-vendors-style-css"
          href="/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-vendors-styled01d.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="wc-blocks-style-css"
          href="/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-styled01d.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="jquery-selectBox-css"
          href="/wp-content/plugins/yith-woocommerce-wishlist/assets/css/jquery.selectBox7359.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="yith-wcwl-font-awesome-css"
          href="/wp-content/plugins/yith-woocommerce-wishlist/assets/css/font-awesome1849.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="woocommerce_prettyPhoto_css-css"
          href="/wp-content/plugins/woocommerce/assets/css/prettyPhoto005e.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="yith-wcwl-main-css"
          href="/wp-content/plugins/yith-woocommerce-wishlist/assets/css/stylef416.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="classic-theme-styles-css"
          href="/wp-includes/css/classic-themes.min68b3.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="contact-form-7-css"
          href="/wp-content/plugins/contact-form-7/includes/css/stylesd96d.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="woocommerce-layout-css"
          href="/wp-content/plugins/woocommerce/assets/css/woocommerce-layoutbdeb.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="woocommerce-smallscreen-css"
          href="/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreenbdeb.css"
          type="text/css"
          media="only screen and (max-width: 768px)"
        />
        <link
          rel="stylesheet"
          id="woocommerce-general-css"
          href="/wp-content/plugins/woocommerce/assets/css/woocommercebdeb.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="yith-quick-view-css"
          href="/wp-content/plugins/yith-woocommerce-quick-view/assets/css/yith-quick-view2c75.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="bootstrap-css"
          href="/wp-content/themes/weefly/assets/css/bootstrap.min5b31.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="fontawesome-min-css"
          href="/wp-content/themes/weefly/assets/css/fontawesome.minf658.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="font-4-min-css"
          href="/wp-content/themes/weefly/assets/css/font-4.min1849.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="simpleline-icon-css"
          href="/wp-content/themes/weefly/assets/css/simple-line-icons8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="magnific-popup-css"
          href="/wp-content/themes/weefly/assets/css/magnific-popup8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="rangeslider-css"
          href="/wp-content/themes/weefly/assets/css/ion.rangeSlider.mina1ec.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="perfect-scrollbar-css"
          href="/wp-content/themes/weefly/assets/css/perfect-scrollbar8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="animate-css"
          href="/wp-content/themes/weefly/assets/css/animate8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="slick-css"
          href="/wp-content/themes/weefly/assets/css/slick.min8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="slick-theme-css"
          href="/wp-content/themes/weefly/assets/css/slick-theme8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="nice-select-css"
          href="/wp-content/themes/weefly/assets/css/nice-select8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="baugette-box-css"
          href="/wp-content/themes/weefly/assets/css/baguetteBox.minc245.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="weefly-woocommerce-css"
          href="/wp-content/themes/weefly/css/woocommerce8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="weefly-stylesheet-css"
          href="/wp-content/themes/weefly/css/main8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="weefly-style-css"
          href="/wp-content/themes/weefly/style8a54.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="weefly-google-fonts-css"
          href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800;900&amp;family=Open+Sans:wght@300;400;500;600;700;800&amp;display=swap"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          id="js_composer_front-css"
          href="/wp-content/plugins/js_composer/assets/css/js_composer.mine1b2.css"
          type="text/css"
          media="all"
        />
        <link rel="https://api.w.org/" href="/wp-json/index.html" />
        <link
          rel="alternate"
          type="application/json"
          href="/wp-json/wp/v2/pages/148.json"
        />
        <link
          rel="EditURI"
          type="application/rsd+xml"
          title="RSD"
          href="/xmlrpc0db0.php?rsd"
        />
        <link
          rel="wlwmanifest"
          type="application/wlwmanifest+xml"
          href="/wp-includes/wlwmanifest.html"
        />
        <meta name="generator" content="WordPress 6.1.1" />
        <meta name="generator" content="WooCommerce 6.7.0" />
        <link rel="canonical" href="index.html" />
        <link rel="shortlink" href="index.html" />
        <link
          rel="alternate"
          type="application/json+oembed"
          href="/wp-json/oembed/1.0/embedd734.json?url=https%3A%2F%2Fslidesigma.com%2Fthemes%2Fwp%2Fweefly%2F"
        />
        <link
          rel="alternate"
          type="text/xml+oembed"
          href="/wp-json/oembed/1.0/embed70b6?url=https%3A%2F%2Fslidesigma.com%2Fthemes%2Fwp%2Fweefly%2F&amp;format=xml"
        />

        <link
          href="https://fonts.googleapis.com/css?family=Open+Sans:400%2C600%7CPlayfair+Display:700%7CNunito:400%7CRoboto:400%7CUbuntu:300%2C400%2C500&amp;display=swap"
          rel="stylesheet"
          property="stylesheet"
          media="all"
          type="text/css"
        />
        <link
          rel="preload"
          as="font"
          id="rs-icon-set-revicon-woff"
          href="/wp-content/plugins/revslider/public/assets/fonts/revicons/revicons90c6.woff"
          type="font/woff"
          crossOrigin="anonymous"
          media="all"
        />
        <link
          rel="preload"
          as="font"
          id="rs-icon-set-fa-icon-woff"
          type="font/woff2"
          crossOrigin="anonymous"
          href="/wp-content/plugins/revslider/public/assets/fonts/font-awesome/fonts/fontawesome-webfont3e6e.woff2?v=4.7.0"
          media="all"
        />
        <link
          rel="stylesheet"
          property="stylesheet"
          id="rs-icon-set-fa-icon-css"
          href="/wp-content/plugins/revslider/public/assets/fonts/font-awesome/css/font-awesome.css"
          type="text/css"
          media="all"
        />
        <link
          rel="stylesheet"
          property="stylesheet"
          id="rs-icon-set-pe-7s-css"
          href="/wp-content/plugins/revslider/public/assets/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css"
          type="text/css"
          media="all"
        />
      </Head>
      <body className="home page-template-default page page-id-148 wp-embed-responsive weefly-main theme-weefly woocommerce-no-js wpb-js-composer js-comp-ver-6.9.0 vc_responsive">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
